import "./Hero.scss";
import LinkWithIcon from "@/shared/ui/LinkWithIcon";
import PeoplePNG from "./people.png";
import HeroCards from "./HeroCards";
import statisticItems from "../model/statisticItems";
import classNames from "classnames";
import { tabletAndMobileMediaWidth } from "@/shared/config/globalVariables";

const Hero = () => {
	const statisticsColumnCount = 3;
	const statisticsTotalRows = Math.ceil(
		statisticItems.length / statisticsColumnCount,
	);
	const statisticsTargetIndex = tabletAndMobileMediaWidth ? 1 : 2;

	return (
		<section className="hero">
			<div className="hero__text">
				<p className="hero__pre-title">Your Journey to Tomorrow Begins Here</p>
				<h1 className="hero__title">
					Explore the Frontiers of Artificial Intelligence
				</h1>
				<p className="hero__description">
					Welcome to the epicenter of AI innovation. FutureTech AI News is your
					passport to a world where machines think, learn, and reshape the
					future. Join us on this visionary expedition into the heart of AI.
				</p>
			</div>

			<ul className="hero__statistics">
				{statisticItems.map(({ count, description }, index) => {
					/* While it was not possible to independently create conditions for adding classes, an optimized solution generated by AI is presented below. */

					const columnIndex = index % statisticsColumnCount;
					const isOnlyRowSecondItem =
						statisticItems.length === statisticsColumnCount && index === 1;
					const isNotLastRow =
						Math.floor(index / statisticsColumnCount) + 1 < statisticsTotalRows;

					const hasPseudoBottom =
						columnIndex === statisticsTargetIndex && isNotLastRow;

					const hasInlineBordersOnDesktop =
						!tabletAndMobileMediaWidth && columnIndex === 1 && isNotLastRow;

					const hasRightBorderOnMobile =
						tabletAndMobileMediaWidth && columnIndex === 0 && isNotLastRow;
					const hasLeftBorderOnMobile =
						tabletAndMobileMediaWidth && columnIndex === 2 && isNotLastRow;

					return (
						<li
							key={description}
							className={classNames("hero__statistics-item", {
								"hero__statistics-item--has-pseudo-bottom": hasPseudoBottom,
								"hero__statistics-item--has-inline-borders-for-only-row":
									isOnlyRowSecondItem,
								"hero__statistics-item--has-inline-borders-for-some-rows":
									hasInlineBordersOnDesktop,
								"hero__statistics-item--has-right-border-for-some-rows-on-mobile":
									hasRightBorderOnMobile,
								"hero__statistics-item--has-left-border-for-some-rows-on-mobile":
									hasLeftBorderOnMobile,
							})}
						>
							<h2 className="h3">
								{count}
								<span>+</span>
							</h2>
							<p>{description}</p>
						</li>
					);
				})}
			</ul>

			<div className="hero__explore">
				<div className="hero__explore-content">
					<div className="hero__explore-people">
						<img
							src={PeoplePNG}
							alt=""
						/>
					</div>
					<h3 className="h5">Explore 1000+ resources</h3>
					<p>Over 1,000 articles on tech trends and breakthroughs.</p>
					<LinkWithIcon
						title="Explore Resources"
						href="/"
						hasBorder
					/>
				</div>
			</div>
			<HeroCards />
		</section>
	);
};

export default Hero;
