import "./HeroCards.scss";
import cardItems from "../model/cardItems";
import LinkCard from "@/shared/ui/LinkCard";
import { tabletAndMobileMediaWidth } from "@/shared/config/mediaWidthVariables";
import classNames from "classnames";

const heroCardsIcons = import.meta.glob("./*.svg", {
	query: "?react",
	import: "default",
	eager: true,
}) as Record<string, React.FC<React.SVGProps<SVGSVGElement>>>;

const HeroCards = () => {
	const cardsColumnCount = !tabletAndMobileMediaWidth ? 3 : 1;
	const cardsTotalRows = Math.ceil(cardItems.length / cardsColumnCount);

	return (
		<ul className="hero__cards">
			{cardItems.map(({ iconPath, title, subtitle, description }, index) => {
				/* While it was not possible to independently create conditions for adding classes, an optimized solution generated by AI is presented below. */

				const IconComponent = heroCardsIcons[iconPath];

				const columnIndex = index % cardsColumnCount;
				const isNotLastRow =
					Math.floor(index / cardsColumnCount) + 1 < cardsTotalRows;

				const hasPseudoBottom =
					!tabletAndMobileMediaWidth && isNotLastRow && columnIndex === 1;

				const hasRightBorder = !tabletAndMobileMediaWidth && columnIndex === 0;
				const hasLeftBorder = !tabletAndMobileMediaWidth && columnIndex === 2;

				return (
					<li
						key={title}
						className={classNames("hero__cards-item", {
							"hero__cards-item--has-pseudo-bottom": hasPseudoBottom,
							"hero__cards-item--has-right-border": hasRightBorder,
							"hero__cards-item--has-left-border": hasLeftBorder,
						})}
					>
						<LinkCard
							icon={
								IconComponent ? (
									<IconComponent
										width={50}
										height={50}
										aria-hidden="true"
									/>
								) : null
							}
							headingTag="h4"
							href="/"
							title={title}
							subtitle={subtitle}
							description={description}
						/>
					</li>
				);
			})}
		</ul>
	);
};
export default HeroCards;
