import "./Contacts.scss";
import { contactItems } from "../model/contactItems";
import {
	desktopMediaWidth,
	tabletAndMobileMediaWidth,
} from "@/shared/config/mediaWidthVariables";
import classNames from "classnames";
import ContactCard from "./ContactCard";

const Contacts = () => {
	const contactsColumnCount = desktopMediaWidth ? 4 : 2;
	const contactsTotalRows = Math.ceil(
		contactItems.length / contactsColumnCount,
	);

	return (
		<ul className="contacts__list">
			{contactItems.map(({ title, text, links, socials }, index) => {
				/* While it was not possible to independently create conditions for adding classes, an optimized solution generated by AI is presented below. */

				const columnIndex = index % contactsColumnCount;
				const isNotLastRow =
					Math.floor(index / contactsColumnCount) + 1 < contactsTotalRows;

				const hasPseudoBottom =
					!tabletAndMobileMediaWidth &&
					isNotLastRow &&
					(desktopMediaWidth ? columnIndex === 1 : columnIndex === 0);

				const hasLeftBorderOnDesktop = desktopMediaWidth && columnIndex === 0;
				const hasInlineBordersOnDesktop =
					desktopMediaWidth && columnIndex === 2;

				const hasLeftBorderOnTablet =
					!tabletAndMobileMediaWidth && !desktopMediaWidth && columnIndex === 1;

				return (
					<li
						key={title}
						className={classNames("contacts__item", {
							"contacts__item--has-pseudo-bottom": hasPseudoBottom,
							"contacts__item--has-left-border-on-desktop":
								hasLeftBorderOnDesktop,
							"contacts__item--has-inline-borders-on-desktop":
								hasInlineBordersOnDesktop,
							"contacts__item--has-left-border-on-tablet":
								hasLeftBorderOnTablet,
						})}
					>
						<ContactCard
							title={title}
							text={text}
							links={links}
							socials={socials}
						/>
					</li>
				);
			})}
		</ul>
	);
};

export default Contacts;
