import "./Reviews.scss";
import classNames from "classnames";
import SectionHeader from "@/shared/ui/SectionHeader";
import { reviewItems } from "../model/reviewItems";
import Review from "./Review";
import {
	desktopMediaWidth,
	tabletAndMobileMediaWidth,
} from "@/shared/config/globalVariables";

const Reviews = () => {
	const reviewsColumnCount = desktopMediaWidth ? 3 : 2;
	const reviewsTotalRows = Math.ceil(reviewItems.length / reviewsColumnCount);

	return (
		<section className="reviews">
			<SectionHeader
				preTitle="What Our Readers Say"
				title="Real Words from Real Readers"
				linkTitle="View All Testimonials"
				href="/"
			/>

			<ul className="reviews__list">
				{reviewItems
					.slice(0, tabletAndMobileMediaWidth ? 3 : reviewItems.length)
					.map(
						(
							{
								authorPhoto,
								authorName,
								authorLocation,
								starsNumber,
								description,
							},
							index,
						) => {
							/* While it was not possible to independently create conditions for adding classes, an optimized solution generated by AI is presented below. */

							const columnIndex = index % reviewsColumnCount;
							const isNotLastRow =
								Math.floor(index / reviewsColumnCount) + 1 < reviewsTotalRows;

							const hasPseudoBottom =
								!tabletAndMobileMediaWidth &&
								isNotLastRow &&
								(desktopMediaWidth ? columnIndex === 1 : columnIndex === 0);

							const hasRightBorderOnDesktop =
								desktopMediaWidth && columnIndex === 0;
							const hasLeftBorderOnDesktop =
								desktopMediaWidth && columnIndex === 2;

							const hasLeftBorderOnTablet =
								!tabletAndMobileMediaWidth &&
								!desktopMediaWidth &&
								columnIndex === 1;

							return (
								<li
									key={authorName}
									className={classNames("reviews__item", {
										"reviews__item--has-pseudo-bottom": hasPseudoBottom,
										"reviews__item--has-right-border-on-desktop":
											hasRightBorderOnDesktop,
										"reviews__item--has-left-border-on-desktop":
											hasLeftBorderOnDesktop,
										"reviews__item--has-left-border-on-tablet":
											hasLeftBorderOnTablet,
									})}
								>
									<Review
										authorPhoto={authorPhoto}
										authorName={authorName}
										authorLocation={authorLocation}
										starsNumber={starsNumber}
										description={description}
									/>
								</li>
							);
						},
					)}
			</ul>
		</section>
	);
};

export default Reviews;
